(self.AMP=self.AMP||[]).push({n:"amp-auto-ads",v:"1809142227020",f:(function(AMP,_){
var h;function aa(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}function k(a,b){b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(c){return b}};var ba=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;var ca=Object.prototype.toString;self.log=self.log||{user:null,dev:null,userForEmbed:null};var n=self.log;function q(){if(!n.user)throw Error("failed to call initLogConstructor");return n.user};var t=Object.prototype.hasOwnProperty;function u(a){return a||{}};function v(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function w(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};function x(a){this.M=a;this.A=this.D=0;this.w=Object.create(null)}x.prototype.has=function(a){return!!this.w[a]};x.prototype.get=function(a){var b=this.w[a];if(b)return b.access=++this.A,b.payload};
x.prototype.put=function(a,b){this.has(a)||this.D++;this.w[a]={payload:b,access:this.A};if(!(this.D<=this.M)){if(n.dev)a=n.dev;else throw Error("failed to call initLogConstructor");a.warn("lru-cache","Trimming LRU cache");a=this.w;var c=this.A+1,d,e;for(e in a){var f=a[e].access;f<c&&(c=f,d=e)}void 0!==d&&(delete a[d],this.D--)}};u({c:!0,v:!0,a:!0,ad:!0});var y,z;
function A(a){var b;y||(y=self.document.createElement("a"),z=self.UrlCache||(self.UrlCache=new x(100)));var c=b?null:z,d=y;if(c&&c.has(a))a=c.get(a);else{d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=
d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;c&&c.put(a,e);a=e}return a};function B(a,b){var c;if(a.__AMP__EXPERIMENT_TOGGLES)c=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);c=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var d in a.AMP_CONFIG){var e=a.AMP_CONFIG[d];"number"===typeof e&&0<=e&&1>=e&&(c[d]=Math.random()<e)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(d=a.AMP_CONFIG["allow-doc-opt-in"],e=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(var e=
e.getAttribute("content").split(","),f=0;f<e.length;f++)-1!=d.indexOf(e[f])&&(c[e[f]]=!0);Object.assign(c,da(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){d=a.AMP_CONFIG["allow-url-opt-in"];e=a.location.originalHash||a.location.hash;a=Object.create(null);if(e)for(var g;g=ba.exec(e);)f=k(g[1],g[1]),g=g[2]?k(g[2],g[2]):"",a[f]=g;for(e=0;e<d.length;e++)f=a["e-"+d[e]],"1"==f&&(c[d[e]]=!0),"0"==f&&(c[d[e]]=!1)}}var l=c;return!!l[b]}
function da(a){a:{var b;try{b=a.document.cookie}catch(g){b=""}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var c=a[b].trim(),d=c.indexOf("=");if(-1!=d&&"AMP_EXP"==k(c.substring(0,d).trim(),void 0)){a=c.substring(d+1).trim();a=k(a,a);break a}}a=null}var e=a,f=e?e.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<f.length;b++)0!=f[b].length&&("-"==f[b][0]?a[f[b].substr(1)]=!1:a[f[b]]=!0);return a}
function C(a,b){a.experimentBranches=a.experimentBranches||{};var c={},d;for(d in b)if(t.call(b,d))if(t.call(a.experimentBranches,d))c[d]=a.experimentBranches[d];else if(!b[d].isTrafficEligible||!b[d].isTrafficEligible(a))a.experimentBranches[d]=null;else if(!a.experimentBranches[d]&&B(a,d)){var e=b[d].branches,f=e;a.experimentBranches[d]=f[Math.floor(Math.random()*f.length)]||null;c[d]=a.experimentBranches[d]}};function ea(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b}function fa(a){return new Promise(function(b){b(a())})};function D(a,b){a=a.__AMP_TOP||a;return E(a,b)}function F(a){var b=H(a),b=I(b);return E(b,"documentInfo")}function J(a,b){a=H(a);a=I(a);return E(a,b)}function H(a){return a.nodeType?D((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function I(a){a=H(a);return a.isSingleDoc()?a.win:a}function E(a,b){var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function K(a,b,c){a=a.createElement(b);for(var d in c)a.setAttribute(d,c[d]);return a}function ga(a,b){for(var c,d=a;d&&d!==c;d=d.parentElement)if(b(d))return d;return null}function ha(a,b){if(a.closest)return a.closest(b);b=b.toUpperCase();return ga(a,function(a){return a.tagName==b})}var L;
function ia(a,b){if(null==L){var c=a.ownerDocument;try{var d=c.createElement("div"),e=c.createElement("div");d.appendChild(e);L=d.querySelector(":scope div")===e}catch(f){L=!1}}if(L)return a.querySelectorAll(":scope "+b);a.classList.add("i-amphtml-scoped");b=a.querySelectorAll(".i-amphtml-scoped "+b);a.classList.remove("i-amphtml-scoped");return b}
function ja(a){w(a.tagName,"AMP-");if(a.createdCallback)return Promise.resolve(a);if(!a.__AMP_UPG_PRM){var b=new ea;a.__AMP_UPG_PRM=b.promise;a.__AMP_UPG_RES=b.resolve}return a.__AMP_UPG_PRM};function M(a){return J(a,"viewport")};function N(a){var b,c=4096,d=[],e=b&&null!=b.value&&""!==b.value?encodeURIComponent(b.name)+"="+encodeURIComponent(String(b.value)):null,f=c-45;e&&(f-=e.length+1);for(var g=Object.keys(a),l=0;l<g.length;l++){var r=g[l],G=a[r];if(null!=G&&""!==G){var p=encodeURIComponent(r)+"=",m=encodeURIComponent(String(G)),R=p.length+m.length+1;if(R>f){var S=m.substr(0,f-p.length-1).replace(/%\w?$/,"");S&&d.push(p+S);e&&d.push(e);break}d.push(p+m);f-=R}}return d.length?"//pagead2.googlesyndication.com/getconfig/ama?"+
d.join("&"):"//pagead2.googlesyndication.com/getconfig/ama"};var ka={isTrafficEligible:function(a){return!!a.document.querySelector("AMP-AUTO-ADS")},branches:["19861210","19861211"]};var la={isTrafficEligible:function(a){return!!a.document.querySelector("AMP-AUTO-ADS")},branches:["3782001","3782002"]};function ma(a){return a?{top:a.top,bottom:a.bottom,left:a.left,right:a.right}:a};function na(a,b){return"adsense"==a?new O(b):"doubleclick"==a?new P(b):null}function O(a){this.h=a}h=O.prototype;h.isEnabled=function(a){C(a,{"amp-auto-ads-adsense-holdout":la});var b=(a.experimentBranches?a.experimentBranches["amp-auto-ads-adsense-holdout"]:null)||null;return"3782001"!=b};h.isResponsiveEnabled=function(a){C(a,{"amp-auto-ads-adsense-responsive":ka});return"19861210"!=((a.experimentBranches?a.experimentBranches["amp-auto-ads-adsense-responsive"]:null)||null)};
h.getConfigUrl=function(){var a=F(this.h).get(),b=A(a.canonicalUrl).hostname;return N({client:this.h.getAttribute("data-ad-client"),plah:b,ama_t:"amp",url:a.canonicalUrl})};h.getAttributes=function(){return u({type:"adsense","data-ad-client":this.h.getAttribute("data-ad-client")})};h.getDefaultAdConstraints=function(){var a=M(this.h).getSize().height;return{initialMinSpacing:a,subsequentMinSpacing:[{adCount:3,spacing:2*a},{adCount:6,spacing:3*a}],maxAdCount:8}};h.getSizing=function(){return{}};
function P(a){this.h=a}h=P.prototype;h.isEnabled=function(){return!0};h.isResponsiveEnabled=function(){return!1};h.getConfigUrl=function(){var a=F(this.h).get(),b=A(a.canonicalUrl).hostname;return N({client:this.h.getAttribute("data-ad-legacy-client"),plah:b,ama_t:"amp",url:a.canonicalUrl})};h.getAttributes=function(){return u({type:"doubleclick","data-slot":this.h.getAttribute("data-slot"),json:this.h.getAttribute("data-json")})};
h.getDefaultAdConstraints=function(){var a=M(this.h).getSize().height;return{initialMinSpacing:a,subsequentMinSpacing:[{adCount:3,spacing:2*a},{adCount:6,spacing:3*a}],maxAdCount:8}};h.getSizing=function(){var a;a:{var b=this.h.getAttribute("data-experiment");try{a=JSON.parse(b);break a}catch(d){}a=void 0}var c=a;return c?{height:c.height?Number(c.height):250,width:c.width?Number(c.width):void 0}:{}};var oa={type:!0};function Q(a){if(!a.attributes)return{};if("[object Object]"!==ca.call(a.attributes)||Array.isArray(a.attributes))return q().warn("amp-auto-ads","attributes property not an object"),{};var b=a.attributes,c={},d;for(d in b)if(oa[d]||w(d,"data-")){var e=typeof b[d];"number"!=e&&"string"!=e&&"boolean"!=e?q().warn("amp-auto-ads","Attribute type not supported: "+e):c[d]=String(b[d])}else q().warn("amp-auto-ads","Attribute not whitlisted: "+d);return c};var pa=["AMP-SIDEBAR","AMP-APP-BANNER"],qa={1:function(a,b){a.parentNode.insertBefore(b,a)},4:function(a,b){a.parentNode.insertBefore(b,a.nextSibling)},2:function(a,b){a.insertBefore(b,a.firstChild)},3:function(a,b){a.appendChild(b)}};function T(a,b,c,d,e,f,g){this.ampdoc=a;this.C=b;this.l=c;this.T=d;this.P=e;this.K=f;this.H=g;this.F=null;this.j=0}T.prototype.getAdElement=function(){return this.F};
T.prototype.getEstimatedPosition=function(){var a=this;return this.C.getElementLayoutBox(this.l).then(function(b){var c;a:switch(c=b,a.T){case 1:case 2:c=c.top;break a;case 3:case 4:c=c.bottom;break a;default:throw Error("Unknown position");}return c})};
T.prototype.placeAd=function(a,b,c,d){var e=this;return this.getEstimatedPosition().then(function(f){return c.isTooNearAnAd(f).then(function(c){if(c)return e.j=3,e.j;e.F=ra(e,a,b.width);e.P(e.l,e.getAdElement());return sa(e,b,d).then(function(a){return ja(e.getAdElement()).then(function(){return e.getAdElement().whenBuilt()}).then(function(){return e.C.attemptChangeSize(e.getAdElement(),a.height,a.width,a.margins)}).then(function(){e.j=2;return e.j},function(){e.j=1;return e.j})})})})};
function sa(a,b,c){var d=a.C.getViewport(),e=d.getWidth();if(c&&1200>=e){b=d.getHeight();var f=ta(e,b),g=ma(a.H);return J(a.l,"resources").getElementLayoutBox(a.l).then(function(b){var c;(c=a.ampdoc.win.getComputedStyle(a.l))||(c=Object.create(null));c=c.direction;0!==b.left&&(g=g||{},"rtl"==c?g.right=b.left:g.left=-b.left)}).then(function(){return Promise.resolve({width:e,height:f,margins:g})})}return Promise.resolve({height:b.height||250,margins:a.H})}
function ra(a,b,c){b=Object.assign(u({layout:c?"fixed":"fixed-height",height:"0",width:c?c:"auto","class":"i-amphtml-layout-awaiting-size"}),b,a.K);return K(a.ampdoc.win.document,"amp-ad",b)}function ua(a,b){var c=b.placements;if(!c)return q().info("amp-auto-ads","No placements in config"),[];var d=[];c.forEach(function(b){va(a,b,d)});return d}
function va(a,b,c){var d=qa[b.pos];if(d){var e=b.anchor;if(e){var f=U(a.getRootNode(),e);if(f.length){var g=void 0;if(b.style){var l=parseInt(b.style.top_m,10),r=parseInt(b.style.bot_m,10);if(l||r)g={top:l||void 0,bottom:r||void 0}}f.forEach(function(e){if(wa(e,b.pos)){var f=Q(b);c.push(new T(a,J(e,"resources"),e,b.pos,d,f,g))}})}else q().warn("amp-auto-ads","No anchor element found")}else q().warn("amp-auto-ads","No anchor in placement")}else q().warn("amp-auto-ads","No injector for position")}
function U(a,b){var c=b.selector;if(!c)return q().warn("amp-auto-ads","No selector in anchor"),[];var c=[].slice.call(ia(a.documentElement||a,c)),d=b.min_c||0;0<d&&(c=c.filter(function(a){return a.textContent.length>=d}));"number"!=typeof b.index&&b.all||(c=(c=c[b.index||0])?[c]:[]);if(0==c.length)return[];if(b.sub){var e=[];c.forEach(function(a){e=e.concat(U(a,b.sub))});return e}return c}
function wa(a,b){var c=1==b||4==b?a.parentElement:a;if(!c)return q().warn("amp-auto-ads","Parentless anchor with BEFORE/AFTER position."),!1;var d=c;return!pa.some(function(a){return ha(d,a)?(q().warn("amp-auto-ads","Placement inside blacklisted ancestor: "+a),!0):!1})}function ta(a,b){var c=100,d=Math.min(300,b),e=Math.round(a/1.2);return Math.min(Math.max(e,c),d)};function V(a,b,c,d,e){this.L=a.slice(0);this.B=b;this.U=c;this.m=d;this.G=0;this.R=void 0===e?!1:e}V.prototype.run=function(){var a=this;return this.m.isMaxAdCountReached()?fa(function(){return W(a)}):X(this).then(function(b){return b?a.run():W(a)})};function W(a){return{adsPlaced:a.G,totalAdsOnPage:a.m.getAdCount()}}
function X(a){var b=a.L.shift();return b?b.placeAd(a.B,a.U,a.m,a.R).then(function(c){return 2==c?(a.m.addAd(b.getAdElement()),a.G++,!0):X(a)}):(q().info("amp-auto-ads","unable to fulfill ad strategy"),Promise.resolve(!1))};function Y(a,b){this.o=a;this.O=b.initialMinSpacing;this.J=b.subsequentMinSpacing.slice(0).sort(function(a,b){return a.adCount-b.adCount});this.S=b.maxAdCount;this.I=xa(this)}Y.prototype.addAd=function(a){this.o.push(a);this.I=xa(this)};Y.prototype.getAdCount=function(){return this.o.length};Y.prototype.isMaxAdCountReached=function(){return this.getAdCount()>=this.S};Y.prototype.isTooNearAnAd=function(a){return ya(this,a,0)};
function ya(a,b,c){return c>=a.o.length?Promise.resolve(!1):za(b,a.o[c]).then(function(d){return d<a.I?!0:ya(a,b,c+1)})}function za(a,b){return J(b,"resources").getElementLayoutBox(b).then(function(b){return a>=b.top&&a<=b.bottom?0:Math.min(Math.abs(a-b.top),Math.abs(a-b.bottom))})}function xa(a){for(var b=a.getAdCount(),c=a.O,d=0;d<a.J.length;d++){var e=a.J[d];e.adCount<=b&&(c=e.spacing)}return c}
function Aa(a){return[].slice.call(a.getRootNode().getElementsByTagName("AMP-AD")).filter(function(a){return a.parentElement&&"AMP-STICKY-AD"==a.parentElement.tagName?!1:!0})}
function Ba(a,b){b=b.adConstraints;if(!b)return null;var c=M(a).getHeight(),d=Ca(b.initialMinSpacing,c);if(null==d)return q().warn("amp-auto-ads","Invalid initial min spacing"),null;var e=(b.subsequentMinSpacing||[]).map(function(a){var b=a.adCount;if(null==b)return q().warn("amp-auto-ads","No subsequentMinSpacing adCount specified"),null;a=Ca(a.spacing,c);return null==a?(q().warn("amp-auto-ads","Invalid subsequent min spacing"),null):{adCount:b,spacing:a}});return-1!=e.indexOf(null)?null:null==b.maxAdCount?
(q().warn("amp-auto-ads","No maxAdCount specified"),null):{initialMinSpacing:d,subsequentMinSpacing:e,maxAdCount:b.maxAdCount}}function Ca(a,b){if(!a)return null;var c=parseFloat(a);return isNaN(c)||0>c?null:v(a,"px")?c:v(a,"vp")?c*b:null};function Da(a,b,c){this.ampdoc=a;this.B=b;this.N=c}
Da.prototype.run=function(){var a;a:{if(a=this.N.optInStatus)for(var b=0;b<a.length;b++)if(2==a[b]){a=!0;break a}a=!1}if(!a)return Promise.resolve(!1);if(0<this.ampdoc.getRootNode().getElementsByTagName("AMP-STICKY-AD").length)return q().warn("amp-auto-ads","exists <amp-sticky-ad>"),Promise.resolve(!1);D(this.ampdoc.win,"extensions").installExtensionForDoc(this.ampdoc,"amp-sticky-ad");a=M(this.ampdoc).getWidth();b=Object.assign({},this.B,u({width:String(a),height:"100"}));a=this.ampdoc.win.document;
b=K(a,"amp-ad",b);a=K(a,"amp-sticky-ad",u({layout:"nodisplay"}));a.appendChild(b);b=this.ampdoc.getBody();b.insertBefore(a,b.firstChild);return Promise.resolve(!0)};function Z(a){return AMP.BaseElement.apply(this,arguments)||this}aa(Z,AMP.BaseElement);
Z.prototype.buildCallback=function(){var a=this;q().assert(B(this.win,"amp-auto-ads"),"Experiment is off");var b=this.element.getAttribute("type");q().assert(b,"Missing type attribute");var c=na(b,this.element);q().assert(c,"No AdNetworkConfig for type: "+b);if(c.isEnabled(this.win)){var d=this.getAmpDoc();D(this.win,"extensions").installExtensionForDoc(d,"amp-ad");var e=J(this.getAmpDoc(),"viewer"),f=e.whenFirstVisible();f.then(function(){return Ea(a,c.getConfigUrl())}).then(function(b){if(b){var e=
b.noConfigReason;if(e)a.user().warn("amp-auto-ads",e);else{var f=ua(d,b),g=Object.assign(c.getAttributes(),Q(b)),p=c.getSizing(),m=Ba(d,b)||c.getDefaultAdConstraints(),m=new Y(Aa(d),m);(new V(f,g,p,m,c.isResponsiveEnabled(a.win))).run();(new Da(d,g,b)).run()}}})}};Z.prototype.isLayoutSupported=function(){return!0};
function Ea(a,b){var c={mode:"cors",method:"GET",credentials:"omit",requireAmpResponseSourceOrigin:!1};return D(a.win,"xhr").fetchJson(b,c).then(function(a){return a.json()}).catch(function(b){a.user().error("amp-auto-ads","amp-auto-ads config xhr failed: "+b);return null})}(function(a){a.registerElement("amp-auto-ads",Z)})(self.AMP);
})});
//# sourceMappingURL=amp-auto-ads-0.1.js.map

